"""empty message

Revision ID: 533e7a7afa75
Revises: 
Create Date: 2020-05-29 17:54:57.066583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533e7a7afa75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'photo')
    # ### end Alembic commands ###
